name = "DGAlgorithms"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DGAlgorithms"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
pp.proofs.withType = false

[[require]]
name = "algolean"
scope = "Shreyas4991"
rev = "v4.30.0"

[[lean_lib]]
name = "DGAlgorithms"
